### ISSUE TITLE
Regarding assignment 2

### ISSUE THREAD

**Issue by innovation-stack** [PriyanshiBhola/ng_freshers_assignment#1]
Referencing DOM node is not angular's way of doing things.
Instead we can write like this:
`<tr *ngFor="let todo of data" [ngClass]="{active: todo === selectedTodo}" (click)="inputClass(todo)">`

```
inputClass(todo) {
  this.selectedTodo = todo;
}

```

**Comment by PriyanshiBhola** [comment]
Thank you, I will implement this
